name: Run tests

on:
  workflow_dispatch:

jobs:
  reference_architecture_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate
        id: authentication
        uses: binbashar/github-app-authentication-action@v1
        with:
          appId: ${{ secrets.GHAPP_APP_ID }}
          clientId: ${{ secrets.GHAPP_CLIENT_ID }}
          privateKey: ${{ secrets.GHAPP_PRIVATE_KEY }}
          installationId: ${{ secrets.GHAPP_INSTALLATION_ID }}

      - name: Run Reference Architecture Tests
        uses: binbashar/trigger-workflow-and-wait@v1.6.3
        with:
          owner: binbashar
          repo: le-tf-infra-aws
          github_token: ${{ steps.authentication.output.token }}
          workflow_file_name: leverage-cli-test.yml
          client_payload: '{"leverage_branch": ${{ github.ref }}}'
